version: '2'
services:
    wi4solutions-app:
        image: wi4solutions
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://wi4solutions-mysql:3306/wi4solutions?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    wi4solutions-mysql:
        extends:
            file: mysql.yml
            service: wi4solutions-mysql
